/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

module T4TS {
    /** Generated from Proofted.Web.Models.Proofing.Invitation **/
    export interface Invitation extends breeze.Entity {
        InvitationId(value?: number): number;
        OrganizationId(value?: number): number;
        Organization(value?: T4TS.Organization): T4TS.Organization;
        EmailAddress(value?: string): string;
        Guid(value?: string): string;
        Used(value?: bool): bool;
    }
    /** Generated from Proofted.Web.Models.Proofing.Organization **/
    export interface Organization extends breeze.Entity {
        Name(value?: string): string;
        OrganizationId(value?: number): number;
        Projects(value?: T4TS.Project[]): T4TS.Project[];
        Tags(value?: any[]): any[];
        Users(value?: any[]): any[];
        Invitations(value?: T4TS.Invitation[]): T4TS.Invitation[];
    }
    /** Generated from Proofted.Web.Models.Proofing.Project **/
    export interface Project extends breeze.Entity {
        Description(value?: string): string;
        Name(value?: string): string;
        ProjectFiles(value?: any[]): any[];
        ProjectId(value?: number): number;
        Tags(value?: any[]): any[];
        OrganizationId(value?: number): number;
        Organization(value?: T4TS.Organization): T4TS.Organization;
    }
}
