// <auto-generated />
namespace Proofted.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class InitialProofing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialProofing));
        
        string IMigrationMetadata.Id
        {
            get { return "201212110417405_InitialProofing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
