// <auto-generated />
namespace Proofted.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class InvitationEnhancements : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InvitationEnhancements));
        
        string IMigrationMetadata.Id
        {
            get { return "201302060010459_InvitationEnhancements"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
