// <auto-generated />
namespace Proofted.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UserSchemaChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserSchemaChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201301230122575_UserSchemaChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
