namespace Proofted.Web.DynamicData.PageTemplates
{
	using System;
	using System.Web.DynamicData;
	using System.Web.UI;
	using System.Web.UI.WebControls;

	public partial class ListDetails : System.Web.UI.Page
    {
        protected MetaTable table;

        protected void Page_Init(object sender, EventArgs e)
        {
            this.table = DynamicDataRouteHandler.GetRequestMetaTable(this.Context);
            this.GridView1.SetMetaTable(this.table, this.table.GetColumnValuesFromRoute(this.Context));
            this.FormView1.SetMetaTable(this.table);
            this.GridDataSource.EntityTypeFilter = this.table.EntityType.Name;
            this.DetailsDataSource.EntityTypeFilter = this.table.EntityType.Name;

        }

        protected void Page_Load(object sender, EventArgs e)
        {
            this.Title = this.table.DisplayName;
            this.GridDataSource.Include = this.table.ForeignKeyColumnsNames;
            this.DetailsDataSource.Include = this.table.ForeignKeyColumnsNames;

            // Selection from url
            if (!this.Page.IsPostBack && this.table.HasPrimaryKey)
            {
                this.GridView1.SelectedPersistedDataKey = this.table.GetDataKeyFromRoute();
                if (this.GridView1.SelectedPersistedDataKey == null)
                {
                    this.GridView1.SelectedIndex = 0;
                }
            }

            // Disable various options if the table is readonly
            if (this.table.IsReadOnly)
            {
                this.DetailsPanel.Visible = false;
                this.GridView1.AutoGenerateSelectButton = false;
                this.GridView1.AutoGenerateEditButton = false;
                this.GridView1.AutoGenerateDeleteButton = false;
                this.GridView1.EnablePersistedSelection = false;
            }
        }

        protected void GridView1_DataBound(object sender, EventArgs e)
        {
            if (this.GridView1.Rows.Count == 0)
            {
                this.FormView1.ChangeMode(FormViewMode.Insert);
            }
        }

        protected void Label_PreRender(object sender, EventArgs e)
        {
            Label label = (Label)sender;
            DynamicFilter dynamicFilter = (DynamicFilter)label.FindControl("DynamicFilter");
            QueryableFilterUserControl fuc = dynamicFilter.FilterTemplate as QueryableFilterUserControl;
            if (fuc != null && fuc.FilterControl != null)
            {
                label.AssociatedControlID = fuc.FilterControl.GetUniqueIDRelativeTo(label);
            }
        }

        protected void DynamicFilter_FilterChanged(object sender, EventArgs e)
        {
            this.GridView1.EditIndex = -1;
            this.GridView1.PageIndex = 0;
            this.FormView1.ChangeMode(FormViewMode.ReadOnly);
        }

        protected void GridView1_RowEditing(object sender, EventArgs e)
        {
            this.FormView1.ChangeMode(FormViewMode.ReadOnly);
        }

        protected void GridView1_SelectedIndexChanging(object sender, EventArgs e)
        {
            this.GridView1.EditIndex = -1;
            this.FormView1.ChangeMode(FormViewMode.ReadOnly);
        }

        protected void GridView1_RowCreated(object sender, GridViewRowEventArgs e)
        {
            this.SetDeleteConfirmation(e.Row);
        }

        protected void GridView1_RowDeleted(object sender, GridViewDeletedEventArgs e)
        {
            this.FormView1.DataBind();
        }

        protected void GridView1_RowUpdated(object sender, GridViewUpdatedEventArgs e)
        {
            this.FormView1.DataBind();
        }

        protected void FormView1_ItemDeleted(object sender, FormViewDeletedEventArgs e)
        {
            this.GridView1.DataBind();
        }

        protected void FormView1_ItemUpdated(object sender, FormViewUpdatedEventArgs e)
        {
            this.GridView1.DataBind();
        }

        protected void FormView1_ItemInserted(object sender, FormViewInsertedEventArgs e)
        {
            this.GridView1.DataBind();
        }

        protected void FormView1_ModeChanging(object sender, FormViewModeEventArgs e)
        {
            if (e.NewMode != FormViewMode.ReadOnly)
            {
                this.GridView1.EditIndex = -1;
            }
        }

        protected void FormView1_PreRender(object sender, EventArgs e)
        {
            if (this.FormView1.Row != null)
            {
                this.SetDeleteConfirmation(this.FormView1.Row);
            }
        }

        private void SetDeleteConfirmation(TableRow row)
        {
            foreach (Control c in row.Cells[0].Controls)
            {
                LinkButton button = c as LinkButton;
                if (button != null && button.CommandName == DataControlCommands.DeleteCommandName)
                {
                    button.OnClientClick = "return confirm('Are you sure you want to delete this item?');";
                }
            }
        }

    }
}
